### ISSUE TITLE
Chat box is not visible

### ISSUE THREAD

**Issue by Urkaz** [Syrious/foundryvtt-sheet-only#16]
As GM or as a player without the Sheet Only functionality enabled, the chat box is currently hidden.

Due to this change from a few days ago, it is gone, so no one can write or say anything to the chat:
https://github.com/Syrious/foundryvtt-sheet-only/blame/fc5ee85754456d5699acbaf9fd6eb9bc6bb12f31/styles/main.css#L78-L81

I think that style should be applied dynamically only when the Sheet Only functionality is enabled (it is enabled for that player and is using and screen size smaller than the specified in the settings).

Thanks for your work! :)

**Comment by Syrious** [comment]
Thanks for bringing this issue to my attention. It is fixed in version 1.0.14
