### ISSUE TITLE
[Feature request] Show dnd5e "Group" actors

### ISSUE THREAD

**Issue by Urkaz** [Syrious/foundryvtt-sheet-only#19]
Hi!
I don't know if this is a bug or maybe it's just not supported (at least for now), but it would be good if Group actors (and maybe Vehicles too?) could be displayed in the Actor List sidebar.

I'm using some Group actors in my campaign to represent the party and also a kind of "bag of holding" and it would be good to have those actors displayed in the sidebar too so the players can modify them and see their contents :)

Thank you!

**Comment by Syrious** [comment]
Hey there!

Try setting the ownership of the group actor to the players. The sidebar should show all actors where the player is the owner. Not tested but it should also work if multiple players are the owner of an actor.

Let me know if that worked.

**Comment by Urkaz** [comment]
Hi!
I tested it a bit more, and it seems like using the "All Players" option doesn't make it appear on the sidebar, even if it is set to Owner. But if you set individual permissions for each player, then there it is!

I don't know why it didn't come to mind yesterday when I adjusted the permissions haha

Thank you for your support and your great work with this module :)
