### ISSUE TITLE
[IMPROVEMENT] Mute audio for players

### ISSUE THREAD

**Issue by davidhawbecker** [Syrious/foundryvtt-sheet-only#25]
I ran just this module in V11 5e 2.1.4  with no other modules and have noticed the scene audio still plays on the players device. Is there any way to automatically mute/disable the audio when sheet only is running on a device other than to have each player go into their account and mute their audio? It's a minor issue and if it's too complicated to set up, no worries. It's just an unnecessary function when you're using sheet only at a table for the players to only access their character sheets. They don't need audio in that case.  

I'll be using this mod for the first time at my table in a few weeks and I'm stoked to see how it works. Thanks for developing and sharing this.

**Comment by Syrious** [comment]
Hi,

I noticed this as well recently. I will look into it and see, if I can force Foundry to not play sounds on clients.
Have fun with your session and give me an update, if something did not work as expected :)
