### ISSUE TITLE
[BUG] Actor Change

### ISSUE THREAD

**Issue by McMuffin88** [Syrious/foundryvtt-sheet-only#26]
#### 
![Screenshot 2024-04-22 225949](https://github.com/Syrious/foundryvtt-sheet-only/assets/75749644/43685c03-2655-41e4-a2b7-332914f418c6)

####
Issue description: When I try to switch characters, the old one doesn't close. This leads, for example, with the Moon Druid, to having many actors open side by side and I can no longer switch back.

#### 
Expected behavior:
I expected that the old actor would be closed and the new one opened so that I could switch back and forth accordingly.

#### System & versions
System Dungeons & Dragons Fifth Edition
Version 11 Build 315

#### 
Steps to reproduce the issue: 
Open the actor list, select a different actor. Once there are more than 6 or 7 actors, switching is no longer possible. Switching from vertical to horizontal layout clearly shows the problem. All actors are side by side.

**Comment by Syrious** [comment]
Hi,

I am not quite sure if I understand the issue. Can you create some images? What browser do you use? And what's the sheet-only version?

Appended you see the the current behaviour.

https://github.com/Syrious/foundryvtt-sheet-only/assets/8050391/e8829d11-d6d7-494d-b327-9ae78d3c9526

**Comment by Pandry** [comment]
I was prototyping some hacks to improve responsiveness and I though about this issue (idk if this might be of help):  

https://github.com/Syrious/foundryvtt-sheet-only/assets/17499836/84035550-a24a-444b-a21b-fc11b6863343

**Comment by McMuffin88** [comment]
Hi,
 I Looks Now well.
One more small Bug - Last Chat are Not complete inside :)
![PXL_20240428_155809073 MP](https://github.com/Syrious/foundryvtt-sheet-only/assets/75749644/d24fd4f9-ca23-4d0c-8c8f-e296d8bbe27e)

**Comment by Syrious** [comment]
I see.. As of version 1.1.7 a full screen mode can be enabled. Have a look if the alignment is still off :)

**Comment by Syrious** [comment]
I also changed the actor list behaviour, adding a nice padding at the bottom. The last actor should now be visible
