### ISSUE TITLE
Feature Request (plus enthusiastic feedback): Allow to show rolls and UI messages?

### ISSUE THREAD

**Issue by coffiarts** [Syrious/foundryvtt-sheet-only#3]
First of all: I am absolutely delighted to see this module coming out: I have **so** long waited for a "sheet only" solution that
- supports mobile devices / touch input
- supports Android (just tested sucessfully)
- is game system agnostic (my first test shows that it is NOT only dnd5e like all the rest! It at least seems to work also with td5e)

Never before have I found a mod supporting all of these aspects! This is a breakthrough IMO! Well done!!

Now my idea/request (once you see a good thing, you always want more of it :-D):
Would it be possible to support
- roll animations? 
- UI notifications

Concerning dice rolls: Right now, I can hear the audio for it playing in the background, but there's no animation neither in the client nor in the GM's session. I guess that at least the latter should work, because otherwise you won't even be able to see them on a shared screen like Monk's.
Or am I getting it wrong, and this _is_ already supported?

Anyway, I am really happy to see that this mod exists, and I am eager to see what it will evolve into over time.

**Comment by Syrious** [comment]
Hi,

thanks for your kind words :)

### UI Notifications
What exactly do you mean by that? Do you mean the blue/yellow/red banner that sometimes pops up?

### Roll animation
Do you mean dice animations by Dice so Nice?

The intent is to burden the clients as less as possible by deactivating as much as possible. I actually wanted to deactivate dice rolls completely since I assumed, most players would roll with real dice on the table. But I will look into it to see if I can make it work (at least for the GM/Common Display).

**Comment by Syrious** [comment]
Just checked it out. The GM should see the rolls:

[2023-12-20 09-23-20.webm](https://github.com/Syrious/foundryvtt-sheet-only/assets/8050391/b51782d9-4290-49cb-81bc-f33b584c1f67)

**Comment by Syrious** [comment]
Just checked the Roll animation. Both the GM and the Common Display should see the rolls if the client can roll it. 

_Left side is GM screen, bottom right Common Display. Both see the roll._
[2023-12-20 10-00-00.webm](https://github.com/Syrious/foundryvtt-sheet-only/assets/8050391/6e50b707-b8e5-4fc1-ac5a-44b7049bd3c3)




Making attack and damage rolls (D&D 5e) causes the system to create a chat message. Only there you can choose to make the attack roll or damage roll. Therefor rolling dice would only work for the elements that will trigger the roll popup.

**Comment by coffiarts** [comment]
Thanks for your replies!

**About "UI notifications":**
Yes, I am thinking of those blue/orange/red banners (temporary or permanent) triggered by ui.notifications.(info|warn|error). I am aware that in your approach here these are still shown on the shared screen, so that's good already! Yet I imagine some "use cases" where it might be helpful to also see them in the "sheet only" UI. It's not a vital need, though. Just curious whether this could be implemented with litte effort (maybe as a configurable option?). If it's a bigger thing, it's probably not worth it.

**About dice rolls:**
I may have caused some confusion here (not testing thoroughly enough), sorry. In fact, I might have even forgotten to activate Dice So Nice in the very first try ;-).
After having a closer look, I found out that it actually works with dnd5 (i.e. you're right).
But it does _not_ seem to work with tde5. So my conflusion that your module is (implicitely) compatible with other systems than dnd was perhaps too quick, at least in that point.

Don't bother too much about my ideas. I'll close this issue, as it is quite unspecific, so that I don't cause a rush here.
I'll try to get more in touch with the details of yor mod.
I definitely love it and will follow its development with great interest!

**Comment by Syrious** [comment]
### About "UI notifications"

Yes, it would be possible. In fact I deliberately disabled the notification to avoid messages like "The Scene "<XYZ>" is now viewed but is not displayed because the game Canvas is disabled."

But I will add a toggle to the game setting.

**Comment by Syrious** [comment]
Added the option to toggle Notifications and Canvas-Hiding in version 1.0.4
