### ISSUE TITLE
[IMPROVEMENT] More user friendly "button-container"

### ISSUE THREAD

**Issue by ThePlanplan** [Syrious/foundryvtt-sheet-only#31]
### Is your feature request related to a problem? Please describe.
The buttons could hide informations on some sheets.

### Describe the solution you'd like
To resolve the issue, I added a quick and dirty touch event listener for touch-activated devices. With a swipe from bottom to top, the buttons appear for a few seconds, before hiding again.

### Describe alternatives you've considered
I tried to add a simple button to display the container, but I could not find a good position, the screen being already cramped. A touch event seems the best to be "sheet agnostic" also.

### Additional context
I'm using your module with the Forbidden Lands system, and a customized sheet for small screen devices (that I'm planning on sharing as a "Sheet Only" add-on module once I'm happy with it).

Here a small screenshot :

![buttons-container](https://github.com/Syrious/foundryvtt-sheet-only/assets/144678719/e00657a8-1a57-4a5a-b091-e5b81f3ae63b)

**Comment by Syrious** [comment]
I was planning to make the button bar movable so it can be placed where ever the player needs it to be.
Bit I will also look into your idea. Thanks!

**Comment by Syrious** [comment]
In version 1.1.7 the button bar can now be positioned freely. It always starts at the top left corner
