### ISSUE TITLE
[BUG] No sheet visible 

### ISSUE THREAD

**Issue by sheathompson** [Syrious/foundryvtt-sheet-only#32]
## Before raising an issue
- I've updated everything to their latest versions, foundry is at the latest version, my 5e world is updated as well to the latest version. I have also played around with various screen widths in the settings to no avail.

#### Issue description
When using this addon on my phone or ipad, no character sheet shows when signing into an account on the device to my server. The page shows blank, no map which is good, a small menu in the lower right corner with no option for the character sheet.

#### Expected behavior
For the character sheet to show when signing in on a mobile device

#### System & versions
All the latest versions

Module-Version: ...
The latest version that was just released on Patreon a few days ago

**Comment by Syrious** [comment]
Can you check, if the player you are logging in with is the owner of an actor?


<img width="295" alt="image" src="https://github.com/Syrious/foundryvtt-sheet-only/assets/8050391/5178c386-6a54-42d8-876e-7c78bca3f37d">

**Comment by sheathompson** [comment]
Sure, I just double checked and yes it is the owner of that actor

**Comment by Syrious** [comment]
Hm, I just asked friends to test it with an older iPad Pro and an older iPhone and it worked. 
Let's try to narrow it down:

- Does it work when you connect via a computer?  
- Have you tried different browsers?
- Can you create an empty world with a bare minimum setup and check if it works?
- Do you have any other modules enabled?
- In Sheet-Only settings did you set the "Activation Screen Width" to anything else than zero? 
- When Sheet-Only is **disabled** can you connect to the game from your iPad and open the sheet manually?

**Comment by Syrious** [comment]
Hey there,

try the new version 1.1.7. I changed some code so the module will check periodically, if an actor owned by the user exists
