### ISSUE TITLE
[BUG] Can't use on-screen keyboard

### ISSUE THREAD

**Issue by deaDleSs-balLoon** [Syrious/foundryvtt-sheet-only#36]
## Before raising an issue
Everything is updated.  
Created a new world without any but this module.  
I'm using android tablet. Tried the same on my smartphone with the same effect.
Tried chrome, firefox and mi browser on tablet. Chrome on smartphone.

#### Issue description

**New dnd5e sheet:** keyboard appears for a moment and then goes away when taping an input box. Tried Microsoft Swiftkey and Gboard.  

**Legacy sheet:** keyboard is there but nothing is changing in the box. Popup dialogs fall behind when tapping an input box. If you zoom out the sheet and so can see popup again, you can input whatever you want.

Found a workaround: you should login while in album orientation, so module is not activated. Then switch to portrait mode and manually open character sheet. Sheet opens scaled to the screen size,  you don't have overlay menu controls, but keyboard is working ok.

#### System & versions
foundry 11.315
Module-Version: 1.1.8
Game-System: dnd5e 3.1.2

PS. Also I don't understand what is the comfortable way to see the spell description in the new dnd5e sheet. The only way I found is to select edit from the popup menu, but this is too complicated comparing to the dropdown by one tap in legacy sheet.

**Comment by Syrious** [comment]
Hi,

thanks for bringing this issue to my attention. It will be fixed in the next version.

**Comment by deaDleSs-balLoon** [comment]
Just tested v1.1.9. It's behaving much better now - you can type into the input fields on the sheet itself. But if you want to make changes in the popup dialog, for example to change maximum hits, you can input the new value but can not save it, because the dialog falls behind the sheet at the same moment you leave the input field. You need to zoom out the sheet as you did in the v1.1.8 so the dialog is visible again. Then you can push the button to save.
