### ISSUE TITLE
Can't save new values in popup dialogs

### ISSUE THREAD

**Issue by deaDleSs-balLoon** [Syrious/foundryvtt-sheet-only#38]
Just tested v1.1.9. It's behaving much better now - you can type into the input fields on the sheet itself. But if you want to make changes in the popup dialog, for example to change maximum hits, you can input the new value but can not save it, because the dialog falls behind the sheet at the same moment you leave the input field. You need to zoom out the sheet as you did in the v1.1.8 so the dialog is visible again. Then you can push the button to save.

_Originally posted by @deaDleSs-balLoon in https://github.com/Syrious/foundryvtt-sheet-only/issues/36#issuecomment-2096884171_

I'm not sure if my comment in the closed issue can be viewed by the author, so I better will open the new one.

PS. Thank you for your great work, it's making the gaming experience so much better!

**Comment by Syrious** [comment]
Hey,

It should get fixed with the new version later today.

I recon that you're using the legacy sheet for editing the character? With the new version your players will be able to edit the new sheet, too.

**Comment by deaDleSs-balLoon** [comment]
> I recon that you're using the legacy sheet for editing the character? 
Yes, we we use legacy sheet or tidy 5e sheet. But the main reason is not editing problem - I can't figure out how to comfortably view spell details (and anything else that pops up on hover event when on PC) in the new sheet on touch devices.

**Comment by Syrious** [comment]
Oh, I didn't know that. Well I checked it out and was able to create tooltips on click.

It does not work when clicking on the name of the entry, as seen in this short video. This change will come with the version 1.1.11


https://github.com/Syrious/foundryvtt-sheet-only/assets/8050391/69c36f98-3de9-4af1-9f3f-4800151c5a88
