### ISSUE TITLE
Feature - Default 5th Edition Sheet break flex

### ISSUE THREAD

**Issue by ZeroXNoxus** [Syrious/foundryvtt-sheet-only#5]
I was wondering if you could change the layout of the default character sheet by breaking the eg. "Attributes" tab, moving Reources, Death Saves, Exhaustion, Inspiration, etc. below Attributes and Skills? This would really help to reduce the left-right scrolling on mobile.

This could also be done with the Navigation bar (Attributes, Inventory, Features, Spellbook, etc) and the Header block (HP, Hit Dice, Armor Class, etc.)

Otherwise I am really impressed! The sheet looks really clean and works wonderfully on my Pixel 8 Pro. Keep up the good work, this should be impelemented by the Foundry team as the official responsive sollution for smartphones imho.

**Comment by ZeroXNoxus** [comment]
I have done some tweaking and this could be done (some-what) easily by tweaking the "flex" and "flex-wrap" properties. It could look like this:
![image](https://github.com/Syrious/foundryvtt-sheet-only/assets/29397572/e1995e05-fa43-4e24-a5fe-2b1a23b5f16d)

**Comment by Syrious** [comment]
Thanks for your contribution ❤️ I'll have a look probably later that day

**Comment by Syrious** [comment]
Added a max-width so it wouldn't look awkward on bigger screens but all in all I very like it!
Works also pretty well for other systems (Tested: The Dark Eye and Level Up: A5E).

Thank's for the help!
