### ISSUE TITLE
[IMPROVEMENT] Full screen chat window for mobile (or below certain screen width)

### ISSUE THREAD

**Issue by BadIdeasBureau** [Syrious/foundryvtt-sheet-only#51]
### Is your feature request related to a problem? Please describe.
The drag and drop chat is great on tablets.  On a mobile device, it's easy for the chat to end up obscuring the sheet-only control buttons, or to drag it such that the latest messages are off the window.

### Describe the solution you'd like
A setting such that, below a certain screen width, the chat would display as a full screen window (i.e. in place of the displayed actor sheet)

### Describe alternatives you've considered
Ensuring that the control buttons are always visible above the chat would help - but once you get to a small screen, the ability to drag and drop the chat just isn't all that useful (since it's obscuring most of the screen anyway), and a full-screen chat would make it easier to interact with chat messages.

**Comment by Syrious** [comment]
Hey there,

thanks for suggesting it. In version 1.4.4 you can check/uncheck an option in sheet-only settings whether the chat should be displayed fullscreen. The button bar has been altered slightly, so it will be stay on top of the chat window.

I hope this helps. But keep in mind that sheet-only uses the system's default sheets, which are not meant to be used on small displays like a smartphone. To get handle stuff like inventory and spells, please check out [Mobile Companion](https://foundryvtt.com/packages/mobile-companion)
