### ISSUE TITLE
[BUG] Settings Buttons are not visible

### ISSUE THREAD

**Issue by jeremyglebe** [Syrious/foundryvtt-sheet-only#63]
#### Issue description
The settings buttons described (Zoom buttons) do not appear when using the module.

#### Expected behavior
Zoom buttons are there.

#### System & versions
Savage Worlds, Foundry v12, latest

Module-Version: ...
Latest

#### Steps to reproduce the issue
Please give me a short step-by-step instruction to reproduce the issue

1. Login as sheet only user

I've noticed in the html the buttons have their style set not to display them. Removing that style makes them work. Is something setting this property?

**Comment by Syrious** [comment]
I'm certain that this issue has been present in all non-dnd5e systems, but it seems that either no one noticed it until now or nobody bothered to inform me, except for you. So, I genuinely appreciate you bringing it to my attention. Thank you! :)
