### ISSUE TITLE
[BUG] Scrolling leads to drag

### ISSUE THREAD

**Issue by SilverStrings5526** [Syrious/foundryvtt-sheet-only#67]
running into an issue where attempting to scroll through the pages drags and moves whatever happens to be under your finger

**Comment by SilverStrings5526** [comment]
issue is consistent between default, legacy, and tidy sheets

**Comment by Syrious** [comment]
Hey there. When holding your finger at the same position for half a second, the system considers this as a drag-start. I implemented this because Foundry's own window-drag does not work very well. I will consider making the delay time of half a second configurable. Thanks for reporting.

**Comment by SilverStrings5526** [comment]
at present, movement is instantaneous when i tested it. did not hold still at all

**Comment by SilverStrings5526** [comment]
Module Version 1.6.3, 5e, game version 3.3.1, foundry version 12 build 331, both on an old ipad mini and a newer ipad air (neither have the M1 or newer apple chips), safari but i can test on firefox

**Comment by SilverStrings5526** [comment]
update. it seems to be a cross compatibility issue with the TouchVTT module

**Comment by Syrious** [comment]
That makes sense. You can disable the drag feature of sheet only in the settings. You will still be able to move most of the windows, using foundry's built in drag functionality, but it does not work well.
