### ISSUE TITLE
New 5th Edition Changes

### ISSUE THREAD

**Issue by ZeroXNoxus** [Syrious/foundryvtt-sheet-only#8]
So, I have installed [DnD 5th Edition 3.0.0](https://github.com/foundryvtt/dnd5e/releases/tag/release-3.0.0) and the sheet looks wonderful. There are, however, a LOT of changes that break the character sheet for Only Sheet. Let's break it down:
- screenshot is the new sheet (desktop)
- marked red are the areas not visible on narrow screens (mobile)
- marked yellow are areas requring style changes
- marked blue are areas requiring a complete haul-over, as the functionality is not easily adaptable

![Change Areas](https://github.com/Syrious/foundryvtt-sheet-only/assets/29397572/3001967d-726c-41e2-88ca-aceb200cc6ee)

Explanation will come tomorrow as we have almost midnight here

**Comment by ZeroXNoxus** [comment]
(1): New Ability Scores - These are now displayed at the top of the sheet in a single row. We need to apply styling to break the line (maybe after 3) to make them visible on narrow screens.
(2): Ignore, I was stupido.
(3): Saves and Proficiencies - These are now displayed together on the right side. While looking nice, they also need to break to a new line. I'm currently looking into this, but disabling the "grid-template-columns: var(--skills-col-width) 1fr;" from ".dnd5e2.sheet.actor.character .sheet-body .tab-body .col-2" lets us display the Saves & Proficiencies below Tools. However, the Saves should IMO be next to the Ability Scores, so we might need to break-out the tab and prepend it before Skill Checks.
(4): This tab can be shown or hidden. I think we should hide it while on narrow screens since it takes a lot of space. The problem here is the Favorites Tab, which seems to include the Ressources. We could also attempt to reduce the size, though that could need a lot of media styling.
(5): Nex Navigation Float: The most problematic section imho. The now floating buttons could be a problem. Whiel it should be possible to float them in the header of the sheet, this could be a tricky placement. We'll need to look into this first to give players even the chance to cycle through their sheet on narrow screens.

All in all, the new sheet is really neat and doesn't require much more to be frank. Inventory, Spell, Feature lists seem to work fine!

**Comment by ZeroXNoxus** [comment]
So, first up: removing "min-width" from ".dnd5e2.sheet.actor.character" and setting padding top of ".dnd5e2.sheet.actor.character .tab-details .tab-body" to "75px" solved issue 1 for up to 524 vw. 
Then, we need to break the line in half (supports up to 350px vw):
- ".dnd5e2.sheet.actor.character .ability-scores .rows > div": "gap: 1rem; flex-wrap: wrap;"
- ".dnd5e2.sheet.actor.character .ability-scores .ability-score": "flex: 0 0 30%;"
- ".dnd5e2.sheet.actor.character .tab-details .tab-body": "padding-top: 160px;"

**Comment by ZeroXNoxus** [comment]
For 5, we have the issue of positioned elements. Current proposition:
- ".dnd5e2.sheet.actor.character nav.tabs": "flex-direction: row; gap: 0.75rem; z-index: 1; right: 5px; left: auto; top: 104px;"
- ".dnd5e2.sheet.actor.character nav.tabs > .item": "border-radius: 8px;"
- ".dnd5e2.sheet.actor.character nav.tabs > .item::after": "border-radius: 5px; border-left: 1px solid;"
- ".dnd5e2.sheet.actor.character .sheet-header > .left .document-name": "font-size: 2.4rem;"
- ".dnd5e2.sheet.actor.character .sheet-header > .right > div:last-child": "margin-top: -1rem;"

**Comment by Syrious** [comment]
I just merged your PR with some changes. I also moved the "mobile only" setting to the settings dialog and instead of toggling it with a checkbox I added an input field where the toggling screen width can be set on a per player basis.

Thanks again for your contribution! (and sorry, it took me so long)
