### ISSUE TITLE
Sheet + Chat mode

### ISSUE THREAD

**Issue by MaxPat931** [Syrious/foundryvtt-sheet-only#9]
I think it would be a great addition to have a mode that shows just the Sheet and Chat sidebar, if that would be feasible. Since with dnd there's not a lot you can do with spell and weapon usage without being able to click the buttons in chat (unless using other modules as well)

Hacked up screenshot from my 8in tablet, might only make sense in landscape?
![image](https://github.com/Syrious/foundryvtt-sheet-only/assets/86370342/dd853ee5-bc59-4c31-905a-9a35a944b6af)

**Comment by Syrious** [comment]
The basic idea was actually to not use the sheet's functionality for rolling at all. It just should make it easier to share data with between player and GM during an in-person-session. It was intended to still use physical dice. 

But nevertheless I'll look into it to see if I can make it toggleable :)

**Comment by ZeroXNoxus** [comment]
@Syrious this could likely be done in the way I have added the slideable character select overlay.

**Comment by mektigh** [comment]
@Syrious IF you go by shacking that. Maybe give us an option to see the combat tracker aswell!

I really hope you consider to make this extension to the mod becouse its great for live settings.

**Comment by Syrious** [comment]
This will be the next feature and I'm already working on it :)

**Comment by Syrious** [comment]
Please try it out and let me know if that works for you
